name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.2.3)"
        required: true
      next-development-version:
        description: "Next SNAPSHOT (e.g. 1.2.4-SNAPSHOT)"
        required: true

jobs:
  release:
    permissions:
      contents: write
    uses: bloomreach-forge/ci-workflows/.github/workflows/release.yml@v1.0.2
    with:
      version: ${{ inputs.version }}
      next-development-version: ${{ inputs.next-development-version }}
    secrets: inherit
